name: Redeploy Backend Application 

on:
    push:
        branches:
            main

jobs:
    redeploy:
        runs-on: ubuntu-latest
        name: Redeploy Backend
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3
            
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

            - name: Build Docker image
              run: docker build -t ${{secrets.DOCKER_USERNAME}}/mono-backend:latest .
            
            - name: Push Docker Image
              run: docker push ${{secrets.DOCKER_USERNAME}}/mono-backend:latest

            - name: Save SSH Private Key
              run:  |
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
                chmod 700 ~/ssh_key
                
                
            
              


